### ISSUE TITLE
Empty inventory

### ISSUE THREAD

**Issue by MartySVK** [PokemonNXT/Unity#13]
I tried game with last version of Unity, it is working fine, but I have empty inventory.
In console I have this error, do you know, where could be a problem ?

`NullReferenceException: Object reference not set to an instance of an object
Inventory+Item.get_id () (at Assets/Trainers/Inventory.cs:174)
Inventory.GetItem (Int32 id) (at Assets/Trainers/Inventory.cs:119)
Inventory.Add (Int32 id, Int32 quantity) (at Assets/Trainers/Inventory.cs:28)
Trainer.Start () (at Assets/Trainers/Trainer.cs:25)`

**Comment by unsol** [comment]
There was a major redo before this fell apart. You'll have to figure it out yourself.

Good luck!
